### ISSUE TITLE
Using CLOCK_MONOTONIC rather than _RAW in Linux?

### ISSUE THREAD

**Issue by hartwork** [atdt/monotonic#1]
Hi!

I noticed that the current code uses CLOCK_MONOTONIC (value 1) rather than CLOCK_MONOTONIC_RAW (value 4) on Linux
(https://github.com/atdt/monotonic/blob/master/monotonic.py#L101)
and is therefore

> affected by the incremental adjustments performed by adjtime(3) and NTP.

according to `man clock_gettime` on Debian wheezy.

The situation in `/usr/include` is this:

```
$ fgrep -R "define CLOCK_MONOTONIC" /usr/include/ | fgrep -v COARSE
/usr/include/linux/time.h:#define CLOCK_MONOTONIC           1
/usr/include/linux/time.h:#define CLOCK_MONOTONIC_RAW       4
/usr/include/bits/time.h:#   define CLOCK_MONOTONIC     1
/usr/include/bits/time.h:#   define CLOCK_MONOTONIC_RAW     4
/usr/include/x86_64-linux-gnu/bits/time.h:#   define CLOCK_MONOTONIC        1
/usr/include/x86_64-linux-gnu/bits/time.h:#   define CLOCK_MONOTONIC_RAW        4
```

Is this a bug or a feature?

At least in my case of measuring runtimes (and timouts) my current impression is that I would rather use CLOCK_MONOTONIC_RAW, i.e. be not affected by NTP.

What do you think?

Best, Sebastian

**Comment by atdt** [comment]
Hi, sorry for the delay in getting back to you.  `CLOCK_MONOTONIC_RAW` would be better, yes, but it is only available in Linux 2.6.28+. If we use it, we should add a version check, and fall back to `CLOCK_MONOTONIC` for older Linuxes.

**Comment by hartwork** [comment]
Cool, thank you.

**Comment by wuxb45** [comment]
I have been using CLOCK_MONOTONIC_RAW for a long time but turned back to CLOCK_MONOTONIC since _RAW can be 5x to 10x slower than the other on some recent CPUs.
Anyway, _RAW is better in quality so the choice depends on how frequently do you call gettime().
Just for reference:
Some latency numbers:
on a Xeon E5 v4 (Broadwell): 750ns vs 120ns
on a thinkpad x1 laptop (i5 Uxxx): 1200ns vs 170ns
